#!/usr/bin/env python3
"""Pictures shown before the game: the DiHalt logo and the cover (opening).

usage: intro_assets.py OUT_DIR
  in:  assets/intro/dihalt_logo-b1.png  256x212 indexed, palette = the V9990's fixed RGB332
                           colours of BD8 mode (index = GGGRRRBB), shown in B1
       assets/intro/opening.png         the cover artwork (any size, RGB/RGBA), shown in B3:
                           512x424 interlaced, BD8
  out: intro.bin  RLE streams in 16 KiB banks (logo first)
       intro.inc  bank and address of each stream, number of banks

The cover is scaled to the full height (424 lines) keeping its proportions (B3
pixels are square on a 4:3 screen), converted to RGB332 with
Floyd-Steinberg dithering and centred on black.

RLE: c < $80: c + 1 literal bytes follow; $80 <= c < $FF: (c & $7F) + 2 times the
next byte; $FF: end. Streams may cross bank boundaries.
"""
import os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IN = os.path.join(ROOT, 'assets', 'intro')
BANK = 16384
B3_W, B3_H = 512, 424
ASPECT = 1.0                    # width / height of a B3 pixel on screen (square: 512x424 in a 640x480 frame)

def rgb332_palette():
    pal = []
    for c in range(256):
        pal += [((c >> 2) & 7) * 255 // 7, ((c >> 5) & 7) * 255 // 7, (c & 3) * 255 // 3]
    return pal

def rle(data):
    out = bytearray()
    i, n = 0, len(data)
    while i < n:
        j = i
        while j < n and j - i < 128 and data[j] == data[i]:
            j += 1
        if j - i >= 2:
            out += bytes((0x80 | (j - i - 2), data[i]))
            i = j
            continue
        lit = bytearray()
        while i < n and len(lit) < 128 and not (i + 1 < n and data[i + 1] == data[i]):
            lit.append(data[i])
            i += 1
        if not lit:
            lit.append(data[i])
            i += 1
        out.append(len(lit) - 1)
        out += lit
    out.append(0xFF)
    return out

def logo():
    im = Image.open(os.path.join(IN, 'dihalt_logo-b1.png'))
    if im.size != (256, 212) or im.mode != 'P':
        raise SystemExit('dihalt_logo-b1.png: expected a 256x212 indexed PNG, got %s %s' % (im.size, im.mode))
    pal = im.getpalette()
    ref = rgb332_palette()
    for c in set(im.getdata()):
        if tuple(pal[3 * c:3 * c + 3]) != tuple(ref[3 * c:3 * c + 3]):
            raise SystemExit('dihalt_logo-b1.png: colour %d is not the RGB332 colour of that index' % c)
    return im.tobytes()

def opening():
    src = Image.open(os.path.join(IN, 'opening.png')).convert('RGB')
    w = int(round(B3_H * src.width / src.height / ASPECT)) & ~1
    src = src.resize((w, B3_H), Image.LANCZOS)
    pimg = Image.new('P', (1, 1))
    pimg.putpalette(rgb332_palette())
    q = src.quantize(palette=pimg, dither=Image.Dither.FLOYDSTEINBERG)
    full = Image.new('P', (B3_W, B3_H), 0)
    full.putpalette(rgb332_palette())
    full.paste(q, ((B3_W - w) // 2, 0))
    return full, w

def main():
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    full, w = opening()
    full.save(os.path.join(out, 'opening_b3.png'))          # preview of what is shown
    streams = [('LOGO', rle(logo())), ('OPEN', rle(full.tobytes()))]
    blob = bytearray()
    inc = ['; generated by tools/intro_assets.py']
    for name, data in streams:
        inc.append('INTRO_%s_BANK equ %d' % (name, len(blob) // BANK))
        inc.append('INTRO_%s_ADDR equ 0%04Xh' % (name, 0x8000 + len(blob) % BANK))
        blob += data
    nb = (len(blob) + BANK - 1) // BANK
    inc.append('INTRO_NBANKS equ %d' % nb)
    blob += bytes(nb * BANK - len(blob))
    open(os.path.join(out, 'intro.bin'), 'wb').write(blob)
    open(os.path.join(out, 'intro.inc'), 'w').write('\n'.join(inc) + '\n')
    print('intro: logo %d bytes, opening %dx%d %d bytes, %d banks' %
          (len(streams[0][1]), w, B3_H, len(streams[1][1]), nb))

if __name__ == '__main__':
    main()
