#!/usr/bin/env python3
"""Graphics for the V9990 port, from the decoded arcade graphics.

usage: port_assets.py GFX_DIR VRAMSTATS_JSON OUT_DIR

Everything is rotated to the game orientation (the arcade monitor is turned
90 degrees clockwise): hardware pixel (hx, hy) of a tile goes to (7 - hy, hx),
of a sprite to (15 - hy, hx). Pixels are stored as the final colour index
(lookup PROM applied), 4 bits, left pixel in the high nibble.

Outputs:
  planeB.bin   plane B (playfield) patterns, V9990 P1 bitmap layout (256 pixels
               wide, pattern n at x = 8*(n%32), y = 8*(n/32)), for VRAM 40000h:
               code < 128:  n = code + 128*flip + 256*colour        (0..4095)
               code >= 128: n = 4096 + (code-128) + 384*flip + 768*(colour&1)
  planeA.bin   plane A (HUD) patterns for VRAM 00000h: n = (code&255) + 256*(colour&3);
               pixel 0 becomes HUD_BLACK (opaque black), n = 1023 is fully transparent
  sprites.bin  3072 sprites x 128 bytes (16 rows x 8 bytes):
               index = code + 256*(flip + 4*colour), flip bit0 = hardware flip X,
               bit1 = hardware flip Y, colour 0..2
  sprites_raw.bin  1024 sprites x 128 bytes, pixel values before the lookup PROM:
               index = code + 256*flip (colour groups 3..15, recoloured at runtime)
  palettes.asm palette blocks per palette bank (V9990 5-bit RGB, 3 bytes per colour)
"""
import sys, os, json

sys.path.insert(0, os.path.join(os.environ.get('ARCADE', os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'arcade')), 'tools'))
from gfxlib import load, tile_game, sprite_game

def put_pattern(buf, n, g):
    """Write an 8x8 pattern into a 256-pixel-wide 4bpp bitmap."""
    x0, y0 = 8 * (n % 32), 8 * (n // 32)
    for r in range(8):
        off = (y0 + r) * 128 + x0 // 2
        for c in range(0, 8, 2):
            buf[off + c // 2] = (g[r][c] << 4) | g[r][c + 1]

def main():
    gfx, stats, out = sys.argv[1:4]
    os.makedirs(out, exist_ok=True)
    pj, tiles, sprites = load(gfx)
    clut, slut, rgb = pj['char_lookup'], pj['sprite_lookup'], pj['rgb']
    # opaque black substitute for the HUD: an index not used by HUD tiles
    st = json.load(open(stats))
    used = set()
    for code in range(512):
        for v in range(16):
            pass
    # HUD tiles: colour groups 0..3 of the font/icon range; take the indices they produce
    hud_codes = set(range(0, 0xB0))
    for code in hud_codes:
        for grp in (0, 1):
            for row in tiles[code]:
                for v in row:
                    used.add(clut[grp * 16 + v])
    free = [i for i in range(15, 0, -1) if i not in used]
    hud_black = free[0] if free else 15
    # ---- plane B
    nB = 4096 + 1536
    bufB = bytearray(nB // 32 * 8 * 128)
    for code in range(512):
        for flip in (0, 1):
            groups = range(16) if code < 128 else (0, 1)
            for grp in groups:
                lut = [clut[grp * 16 + v] for v in range(16)]
                n = code + 128 * flip + 256 * grp if code < 128 else 4096 + (code - 128) + 384 * flip + 768 * grp
                put_pattern(bufB, n, tile_game(tiles[code], flip, lut))
    open(os.path.join(out, 'planeB.bin'), 'wb').write(bufB)
    # ---- plane A (HUD)
    bufA = bytearray(1024 // 32 * 8 * 128)
    for code in range(256):
        for grp in range(4):
            n = code + 256 * grp
            if n == 1023:
                continue
            lut = [clut[grp * 16 + v] for v in range(16)]
            lut = [hud_black if x == 0 else x for x in lut]
            put_pattern(bufA, n, tile_game(tiles[code], 0, lut))
    open(os.path.join(out, 'planeA.bin'), 'wb').write(bufA)
    # ---- sprites
    spr = bytearray()
    for grp in range(3):
        lut = [slut[grp * 16 + v] for v in range(16)]
        for flip in range(4):
            for code in range(256):
                g = sprite_game(sprites[code], flip & 1, flip >> 1, lut)
                for r in range(16):
                    for c in range(0, 16, 2):
                        spr.append((g[r][c] << 4) | g[r][c + 1])
    open(os.path.join(out, 'sprites.bin'), 'wb').write(spr)
    # raw atlas for the rare colour groups 3..15: recoloured by the runtime when
    # uploaded (index = code + 256 * flip)
    raw = bytearray()
    ident = list(range(16))
    for flip in range(4):
        for code in range(256):
            g = sprite_game(sprites[code], flip & 1, flip >> 1, ident)
            for r in range(16):
                for c in range(0, 16, 2):
                    raw.append((g[r][c] << 4) | g[r][c + 1])
    open(os.path.join(out, 'sprites_raw.bin'), 'wb').write(raw)
    # ---- palettes
    def c5(c):
        return [c[0] >> 3, c[1] >> 3, c[2] >> 3]
    lines = ['; generated by tools/port_assets.py',
             'HUD_BLACK equ %d' % hud_black,
             '; per palette bank 0-7: block 0 (tiles, plane B) then block 1 (HUD, plane A)',
             'pal_banks:']
    for b in range(8):
        bb = b if b < 6 else 5
        blk0 = [c5(rgb[bb * 32 + 16 + i]) for i in range(16)]
        blk1 = [c[:] for c in blk0]
        blk1[hud_black] = [0, 0, 0]
        lines.append('        db ' + ','.join('%d' % x for c in blk0 + blk1 for x in c) + '   ; bank %d' % b)
    lines.append('slut_groups:   ; sprite lookup PROM: 16 colour groups x 16 pixel values -> colour')
    for g in range(16):
        lines.append('        db ' + ','.join('%d' % slut[g * 16 + v] for v in range(16)))
    lines.append('pal_sprites:   ; block 2: the fixed 16 sprite colours')
    lines.append('        db ' + ','.join('%d' % x for i in range(16) for x in c5(rgb[i])))
    open(os.path.join(out, 'palettes.asm'), 'w').write('\n'.join(lines) + '\n')
    print('planeB %d bytes, planeA %d, sprites %d, HUD black index %d' % (len(bufB), len(bufA), len(spr), hud_black))

if __name__ == '__main__':
    main()
